# Generated by Django 5.2.5 on 2025-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_translation',
            field=models.CharField(blank=True, max_length=250, verbose_name='Перевод примера'),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, verbose_name='Часть речи'),
        ),
    ]
