# Generated by Django 5.2.5 on 2025-08-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_word_example_translation_word_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=250, verbose_name='Транскрипция'),
        ),
    ]
